name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"    
    - uses: actions/checkout@v4
    - name: configure
      run: sudo apt-get install -y libgtk-4-1 libgtk-4-dev
    - name: make
      run: make      
    - name: Upload app artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}-${{ steps.date.outputs.date }}
        path: .
  release:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.RELEASE_ACCESS }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: .
